#Sample Ansible playbook using variables

-
 name: Add DNS server to resolv.conf
 hosts: localhost
 vars:
  dns_server:10.1.112.23
 tasks:
        - lineinfile
            path: /etc/resolv.conf
            line: 'nameserver {{dns_server}}' # Jinja2 Templating